### ISSUE TITLE
publish-vsx-latest build error 

### ISSUE THREAD

**Issue by yiliang114** [eclipse-theia/vscode-builtin-extensions#111]
![image](https://user-images.githubusercontent.com/11473889/226808533-ab3098d9-e4d4-4356-a3ec-4d1c4e940783.png)

**Comment by marcdumais-work** [comment]
Hi @yiliang114 ,

Thanks for opening this issue. Note that we disabled publishing during the normal CI run, since we want to manage more closely what gets published. So, we can fix the workflow, but it will not immediately result in new vscode built-in extensions being published nightly. 

Rather we manually publish by pushing to a special branch:
https://github.com/eclipse-theia/vscode-builtin-extensions#re-publishing-individual-built-in-vscode-extensions-and-built-in-extension-packs-to-open-vsx
