### ISSUE TITLE
builtin notebook renderers not built correctly

### ISSUE THREAD

**Issue by jonah-iden** [eclipse-theia/vscode-builtin-extensions#121]
Hi, the [builtin notebook renderer](https://open-vsx.org/extension/vscode/builtin-notebook-renderers/1.66.2) extension seems to not being built correctly. 
There is no published version 1.77.0 like for the other builtin extensions and the compiled files from the `renderer-out` folder are missing in both exisiting vsix bundles.

**Comment by jonah-iden** [comment]
@vince-fugnitto could you take a look if you find the time. This is pretty important for the theia builtin notebook support

**Comment by vince-fugnitto** [comment]
@jonah-iden can you let me know if the following plugin works for you (I'm not sure why it was previously skipped for 1.77.0):

- [builtin-notebook-renderers-1.77.0.zip](https://github.com/eclipse-theia/vscode-builtin-extensions/files/12146396/builtin-notebook-renderers-1.77.0.zip)

**Comment by jonah-iden** [comment]
Yeah that seems to work. Thanks for your quick response

**Comment by vince-fugnitto** [comment]
> Yeah that seems to work. Thanks for your quick response

The good thing is the build and packaging seems to work fine (no changes needed). Not sure why it wasn't published however, perhaps it was a decision since we did not have notebook support at the time. Both @marcdumais-work and @alvsan09 are on vacation at this time but I'll post an update when I get in contact with them.

We should also think of publishing 1.78.0 soon since its our latest supported version.

**Comment by vince-fugnitto** [comment]
Note that [vscode.builtin-notebook-renderers@1.79.0](https://open-vsx.org/extension/vscode/builtin-notebook-renderers) has been published successfully.
