### ISSUE TITLE
JS embedded in HTML lacks IntelliSense

### ISSUE THREAD

**Issue by StevieD666** [eclipse-theia/vscode-builtin-extensions#35]
Bug Description:
Languages that support embedded languages in an extension, when editing a part of a file where the embedded language is, IntelliSense doesn't work.

Steps to Reproduce:
Create a HTML file.
Add a SCRIPT tag.
Add some JavaScript code in the tag.
Initiate IntelliSense with Ctrl+Space, in VSCode the language Server is initiated and a list of attributes/functions are displayed, in theia it does not.

**Comment by marcdumais-work** [comment]
Thanks for registering this issue @StevieD666. If it's not too much trouble, I think a couple of short video or screenshots showing, in action, an example of the difference of suggested completion between vscode and a Theia app, would be interesting.

**Comment by marcdumais-work** [comment]
I was able to reproduce. Thanks @StevieD666 for adding [screenshots](https://community.theia-ide.org/t/embedded-language-support/1102/12?u=marcdumais-work) on the forum discussion.

I noticed the following exception in the frontend, every time I try to complete inside a `<script>` block - probably a good place to start investigating:

![image](https://user-images.githubusercontent.com/25749063/95625991-795c9b00-0a47-11eb-9bab-e006dfb29736.png)

**Comment by marcdumais-work** [comment]
I notice too that syntax highlight for embedded JS looks broken in the Theia app (based on latest `next`):

Theia app:
![image](https://user-images.githubusercontent.com/25749063/95626245-ef610200-0a47-11eb-940d-0f3416053069.png)

vscode:
![image](https://user-images.githubusercontent.com/25749063/95626327-10c1ee00-0a48-11eb-81af-00b77418beb4.png)

not necessarily related though

**Comment by vince-fugnitto** [comment]
I just wanted to mention that both `css` and `jquery` completion items (embedded languages) work successfully.
The issue seems to be related to loading **JS/TS** completions:

<div align='center'>


![jquery-items](https://user-images.githubusercontent.com/40359487/96590595-348cfb80-12b4-11eb-8ae7-586da5472f9d.gif)

![css](https://user-images.githubusercontent.com/40359487/96590612-39ea4600-12b4-11eb-86ea-43e5a257d64d.gif)

</div>

**Comment by vince-fugnitto** [comment]
@marcdumais-work I believe it might be an issue on how we build and package the `vscode-builtin-html-language-features` extension (currently the only builtin which provides extensive embedded language-support), namely how `typescript` is added as a dependency.

Looking under the `plugins/` directory for the builtin, I noticed that no `bin` directory is present, and the directory referenced by the extension itself is also missing: 

https://github.com/microsoft/vscode/blob/d2a825f57e422e7b177fdb4ec4650e46f738240d/extensions/html-language-features/build/bundleTypeScriptLibraries.js#L15-L16

```ts
const TYPESCRIPT_LIB_SOURCE = path.join(__dirname, '../../node_modules/typescript/lib');
const TYPESCRIPT_LIB_DESTINATION = path.join(__dirname, '../server/build');
```


![image](https://user-images.githubusercontent.com/40359487/96627741-4d5ed680-12df-11eb-95a0-a921cf95a121.png)

**Comment by marcdumais-work** [comment]
Good catch @vince-fugnitto . 

```typescript
const TYPESCRIPT_LIB_SOURCE = path.join(__dirname, '../../node_modules/typescript/lib');
```

Indeed, here, once packaged as a `vsix` extension, this path will not exist. The reason is that, for `vscode`, these extensions are never packaged, and so they share one `typescript`, in a `node_modules` one directory level above them. Unfortunately, in packaged extensions, that folder maps to each extension's `extension` folder, where nothing can be added as part of `vsix` packaging. 

I think we can patch `bundleTypeScriptLibraries.js` after build to point to the `typescript` we already bundle with the extension, under `server`.

**Comment by StevieD666** [comment]
Thanks for the comments, so it looks like this isn't a global problem with all languages, just an issue with HTML and it's embedded languages?

**Comment by vince-fugnitto** [comment]
> Thanks for the comments, so it looks like this isn't a global problem with all languages, just an issue with HTML and it's embedded languages?

@StevieD666 yes I believe so, more specifically an issue with embedded JS in HTML only (since both embedded CSS and JQuery work correctly). The builtins are special cases as they require some extra manipulation and tweaks in order for them to be isolated in a way (with their dependencies) so that they can be properly packaged and consumed. It looks like we need to update some of the build steps before attempting to package.

**Comment by marcdumais-work** [comment]
> ```ts
> const TYPESCRIPT_LIB_SOURCE = path.join(__dirname, '../../node_modules/typescript/lib');
> ```
> 
>[...]
> 
> I think we can patch `bundleTypeScriptLibraries.js` after build to point to the `typescript` we already bundle with the extension, under `server`.

I did the above a while ago:

https://github.com/eclipse-theia/vscode-builtin-extensions/blob/master/src/package-vsix.js#L85-L87

I just retested using the Theia example application (built from master), and I no longer see this issue. 

It uses this version of the html extension:
"vscode-builtin-html-language-features": "https://open-vsx.org/api/vscode/html-language-features/1.48.0-next.4a1bcdafe9/file/vscode.html-language-features-1.48.0-next.4a1bcdafe9.vsix"

**Comment by mig8447** [comment]
Hello, I cannot get this to work even though I imported the same version of the plugin in the Theia repository, could you help me figure out what's wrong?
