### ISSUE TITLE
List all vscode built-ins

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/vscode-builtin-extensions#40]
There should be a way to get the list of all vscode built-ins of this repo. 
For now the list can be obtained only from the [package.json](https://github.com/eclipse-theia/theia/blob/master/package.json#L86-L154).

**Comment by marcdumais-work** [comment]
(for a given vscode version, I assume - the list can change in time)

I am not sure if this is a great idea, but one way would be to generate and [extension pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup) from all built-in extensions that we build/publish in a run (just references). Looking at the pack's package.json, one could see the list contained.

**Comment by koegel** [comment]
I guess Theia does not support installing extension packs, does it? So the only purpose of the extension pack would be to list all built-ins?

**Comment by marcdumais-work** [comment]
> I guess Theia does not support installing extension packs

It does, but with some limitations, e.g. all extensions, part of a pack, have to be available in your registry (open-vsx.org by default). 

The vscode-builtins are a unique case and pose a special challenge, to be installed with a pack. It's related to the intelligence in the VSX client, that attempts to pick a version of an extension that would likely work, given its stated required vscode API level (`engines.vscode` field in `package.json`). Unfortunately vscode-builtins do not set this field, at all or correctly, and so the mechanism breaks and we end-up installing the latest solid version, I think.

In practice, for a vanilla Theia app, If a user installs a vscode-builtins pack at runtime, they'll not get a fully-working set. Individual extensions will work, but some will not, including some key ones. Which is why for now we hand-pick the exact extensions/versions we want, adding their URLs in the app's `package.json`. Once the VSX client/server get smart enough or we work-around the problem in some other way, we might be able to install all these from one or more packs, as we see fit. 

Potential `vscode-builtins` packs we could publish along with the builtins (under a different namespace I think would be more appropriate):
- `all of them` pack
- `basic syntax highlight support for all languages` pack  (grammars and snippets)
- `advanced web dev` pack  (HTML, TS, ...)
- `recommended` pack (markdown, ...)
- ???

WDYT?

**Comment by koegel** [comment]
Sounds good to me, creating an `all of them` pack would be a good starting point.

**Comment by marcdumais-work** [comment]
I think we'll need this PR merged first, that has some improvements for handling `vscode-builtins` (looking close to being merged): 
https://github.com/eclipse-theia/theia/pull/8191

**Comment by marcdumais-work** [comment]
Ok, then I think we can start by generating a pack that supports all `vscode-builtins` that are likely to work, at the same time we build them, and eventually publish the pack along the individual extensions (using a different namespace - e.g. project name?). 

We could exclude a few like `markdown-language-features` that do not correctly work unless pinned to an old version, to prevent having a bad version installed that can't be updated. 

Or maybe we can make sure that a working version of such extensions are installed before the pack - they should remain unchanged and the pack will still install correctly. To be confirmed.

**Comment by alvsan09** [comment]
Hello,
The proposed implementation to create the built-in 'all of them' pack is ready for you to review, and test
Comments are very welcome, 

When it comes to the next step to select subsets of them, we can follow that up as the next step under issue:
https://github.com/eclipse-theia/vscode-builtin-extensions/issues/58

**Comment by marcdumais-work** [comment]
The `built-in extensions pack` is now published on open-vsx:
https://open-vsx.org/extension/eclipse-theia/builtin-extension-pack/1.50.0

There is a "bundled extensions" section, that lists them. Just the first few:
![image](https://user-images.githubusercontent.com/25749063/118052169-43bac000-b350-11eb-8617-8e32c8163741.png)
