### ISSUE TITLE
GitHub Release: URL for python-1.39.1-prel.visx returns a 403

### ISSUE THREAD

**Issue by snickell** [eclipse-theia/vscode-builtin-extensions#87]
It looks like perhaps something has gone wrong on the GitHub side, but if you try to download the `python-1.39.1-prel.visx` (https://github.com/eclipse-theia/vscode-builtin-extensions/releases/download/v1.39.1-prel/python-1.39.1-prel.vsix)  URL from the  releases page https://github.com/eclipse-theia/vscode-builtin-extensions/releases , I consistently get the following GET error:
![image](https://user-images.githubusercontent.com/223277/134108896-a0f0c9d5-3b1d-4cf1-b816-8619a3c7e340.png)

URLs for the other released `.visx` files appear to work as normal.

**Comment by snickell** [comment]
Workaround: use openvsx to install `ms-python`, currently using `2020.10.332292344`

**Comment by snickell** [comment]
https://open-vsx.org/extension/ms-python/python/2020.10.332292344

**Comment by vince-fugnitto** [comment]
@snickell I am able to successfully download from the github releases.
As you've mentioned, one should use the releases on open-vsx instead, releasing on github releases was only temporary.

**Comment by marcdumais-work** [comment]
@snickell The extension you link on `open-vsx.org` is not the same one though - it's the more advanced one, that provide language intelligence and debug. The built-in python extension, that is causing you download issues, provides the grammar for syntax highlight, which may or may not be provided by `ms-python.python` (probably not - it's assumed you have the built-ins installed). 

Here is the same builtin extension, slightly newer version, that you could use from open-vsx instead of GH downloads: 
https://open-vsx.org/api/vscode/python/1.45.1/file/vscode.python-1.45.1.vsix
